services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sagnus-rabbit
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_PASS: ${SAGNUS_RABBIT_PASS}
      RABBITMQ_DEFAULT_USER: ${SAGNUS_RABBIT_USER}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: sagnus-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sagnus
      POSTGRES_USER: sagnus
      POSTGRES_PASSWORD: sagnus

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data:


